"""add_config_json_to_task

Revision ID: e1aaab98a21f
Revises: fd1abc850b51
Create Date: 2026-03-30 03:41:09.798218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1aaab98a21f'
down_revision: Union[str, None] = 'fd1abc850b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('config_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'config_json')
    # ### end Alembic commands ###
